version: '3.3'

services:
  convert-service:
    image: convert-api
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      JPEG_QUALITY: 80
      SERVICE_NAME: convert-api
      NODE_ENV: production
    ports:
      - 8000:8000